### PR TITLE
fix: Turn 2 links into real buttons (Type a barcode & Select from gallery)

### LINKED ISSUE #329: Turn Type a barcode and Select from gallery into real buttons

### PR DESCRIPTION
**Pull request by ArturLange**
### What

Following #164 & #162

Change **Type a barcode** and **Select from gallery** links to buttons

### Screenshot

||Image|
|--|---|
|Small screens|image|
|Larger screens|image|

### CODE REVIEW

File: src/views/AddPriceSingle.vue [hunk 1]
```diff
@@ -30,7 +30,7 @@
             </h3>
             <v-sheet v-if="productMode === 'barcode'">
               <v-btn class="mb-2 mr-2" size="small" prepend-icon="mdi-barcode-scan" @click="showBarcodeScanner">{{ $t('AddPriceSingle.ProductInfo.ScanBarcode') }}</v-btn>
-              <a href="#" @click.prevent="showBarcodeManualInput">{{ $t('AddPriceSingle.ProductInfo.TypeBarcode') }}</a>
+              <v-btn class="mb-2 mr-2" size="small" prepend-icon="mdi-numeric" @click.prevent="showBarcodeManualInput">{{ $t('AddPriceSingle.ProductInfo.TypeBarcode') }}</v-btn>
```
Comment (raphodn) [inline src/views/AddPriceSingle.vue:33]: I'm wondering if we should have a different behavior on small screens : a shortened version to avoid having 2 lines. Can be done in a different PR of course

image

**Review by raphodn — APPROVED** [review]
:100:

File: src/views/AddPriceSingle.vue (hunk 1 above)
Comment (dq18) [reply src/views/AddPriceSingle.vue:33]: Was about to work on this! But no worries, great that you are helping @ArturLange , greatly needed.
I would shorten also to "Scan" and "Manual" (or similar). I was thinking of just using obvious icons too, like a "camera" icon and a "keypad" icon. Some UI/UX expert or designer input would be great

Comment (raphodn) [reply src/views/AddPriceSingle.vue:33]: The UX "good practice" (at least used at OFF) is to have always icon + text.

I'm adding a commit (and screenshot) to reduce the text on small screens.
