### PR TITLE
fix(utils): relative time display

### LINKED ISSUE #877: Fix the relative time displayed (server timezone ?)
### Story

New prices always show at least "2h" ago, when they should show "Xs" ago or "Xm" ago :)

### Example

Creating this issue at 9:52 AM (French time).
The latest price's relative time shows up with "3h" ago
The latest price's raw timestamp is `2024-09-30T06:38:14.855888Z`
The latest price's tooltip displays 8:38AM

image

### PR DESCRIPTION
**Pull request by TTalex**
### What
- Make new price show  "Xs" ago or "Xm" ago instead of "2h" ago

### Screenshot
| Before | After |
| --- | --- | 
|before|after|

### Fixes bug(s)
- Fixes #877

### CODE REVIEW

File: src/utils.js [hunk 1]
```diff
@@ -126,7 +126,7 @@ function offDateTime(dateTimeString) {
  * changes: add short (replace 'days' with 'd', remove 'Yesterday') & shortest (remove 'ago'), extend days & weeks
  */
 function prettyRelativeDateTime(dateTimeString, size=null) {
-  var date = new Date((dateTimeString || "").replace(/-/g, "/").replace(/[TZ]/g, " ")),
+  var date = new Date((dateTimeString || "")),
```
Comment (raphodn) [inline src/utils.js:129]:
```suggestion
  var date = new Date(dateTimeString || ""),
```

**Review by raphodn — APPROVED** [review]
thank you :innocent:
